openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /v1/customers/{customer_id}:
    get:
      summary: Get a Customer by its id
      description: Get a single Customer by its Id
      parameters:
        - name: customer_id
          in: path
          description: Customer id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Found Customer
          content:
            application/json:
              schema:
                $ref: "https://github.com/brownjasonj/openapi.domain.model/blob/master/schemas/counterparty/counterparty.yaml#counterparty"

components:
  schemas:
    customer:
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
          example: "Kenny"
        lastName:
          type: string
          example: "Doe"
        address:
          $ref: "#/components/schemas/counterparty_address"

    counterparty_address:
      type: object
      properties:
        line1:
          type: string
          example: "123 Main Street"
        city:
          type: string
          example: "South Park"
        stateCode:
          type: string
          minLength: 2
          maxLength: 2
          description: 2 Letter State Code
          enum:
            - AL
            - AZ
            - AK
            - AR
            - CA
        zipCode:
          type: string
          example: "91210"
